name: LLVM

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      BUILD_TYPE: Release
      LLVM_VERSION: 17.0.6
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Download and build LLVM
      run: |
        cmake "-DLLVM_VERSION=${{ env.LLVM_VERSION }}" -P download_llvm.cmake
        cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install-${{ env.LLVM_VERSION }}" -DLLVM_ENABLE_PROJECTS=clang -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_ASSERTIONS=ON -S llvm-${{ env.LLVM_VERSION }}/llvm -B build-${{ env.LLVM_VERSION }}
        cmake --build "build-${{ env.LLVM_VERSION }}"
        cmake --install "build-${{ env.LLVM_VERSION }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: llvm-${{ env.LLVM_VERSION }}-${{ matrix.os }}
        path: install-${{ env.LLVM_VERSION }}
